# Generated by Django 4.0.4 on 2022-04-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('established_year', models.IntegerField()),
                ('current_employees', models.IntegerField(default=0)),
            ],
        ),
    ]
