# Generated by Django 4.0.4 on 2022-04-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companydetails_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='current_employees',
        ),
    ]
