# Generated by Django 4.0.4 on 2022-04-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0002_alter_users_company'),
        ('Company', '0002_alter_companydetails_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_amount', models.IntegerField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companydetails', to_field='company_name')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.users')),
            ],
        ),
    ]
