# Generated by Django 4.0.4 on 2022-04-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companydetails_company_name'),
        ('Account', '0002_alter_users_company'),
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenerateInvoice',
            new_name='InvoiceDetails',
        ),
    ]
